#!/bin/sh
# Generate a vAmiga reference screenshot for a single ADF, for cross-checking
# Copperline against vAmiga on demand.
#
# vAmiga 5.0 also provides the A1200_2MB AGA setup. It runs the ADF headless
# via a RetroShell "regression" script and
# dumps a 716x285 RGB raw framebuffer (the same format tools/vamigats-compare.py
# and tools/vamigats-diffview.py expect as <stem>.vamiga.raw).
#
# Usage:
#   tools/vamiga-ref.sh <adf> [seconds] [setup] [out.vamiga.raw] [kick.rom]
#
#   seconds  wall-clock emulated time before the shot   (default 9)
#   setup    A500_OCS_1MB | A500_ECS_1MB | A500_PLUS_1MB | A1000_OCS_1MB |
#            A1200_2MB
#            (default A500_OCS_1MB)
#   out      where to write the raw                       (default /tmp/<stem>.vamiga.raw)
#   kick     Kickstart ROM                                (default test-assets/kick13.rom)
#
# Env: VAHEADLESS overrides the vAmiga headless binary path.
set -e
cd "$(dirname "$0")/.."
REPO="$(pwd)"

ADF="$1"
SECONDS_ARG="${2:-9}"
SETUP="${3:-A500_OCS_1MB}"
OUT="$4"
KICK="${5:-$REPO/test-assets/kick13.rom}"

VAHEADLESS="${VAHEADLESS:-$HOME/Programming/Git/AmigaMe/vAmiga/Core/build/VAHeadless}"

if [ -z "$ADF" ]; then
    echo "usage: tools/vamiga-ref.sh <adf> [seconds] [setup] [out.raw] [kick.rom]" >&2
    exit 2
fi
if [ ! -x "$VAHEADLESS" ]; then
    echo "error: VAHeadless not found at $VAHEADLESS" >&2
    echo "  build it: cmake -S ~/Programming/Git/AmigaMe/vAmiga/Core -B .../build && cmake --build .../build --target VAHeadless" >&2
    echo "  or set VAHEADLESS=/path/to/VAHeadless" >&2
    exit 1
fi
if [ ! -f "$ADF" ]; then echo "error: no such ADF: $ADF" >&2; exit 1; fi
if [ ! -f "$KICK" ]; then echo "error: no Kickstart: $KICK" >&2; exit 1; fi

stem="$(basename "$ADF")"; stem="${stem%.*}"
[ -z "$OUT" ] && OUT="/tmp/${stem}.vamiga.raw"

# RetroShell wants integer seconds; the screenshot is written to /tmp/<name>.raw.
secs_int=$(awk "BEGIN{printf \"%d\", ($SECONDS_ARG)+0.999}")

# PID-suffixed temp names so concurrent runs (or debris from a crashed one)
# cannot clobber each other's inputs and silently produce a wrong reference.
tmp_kick=/tmp/vamiga-ref-$$-kick.rom
tmp_adf=/tmp/vamiga-ref-$$-disk.adf
# RetroShell tokenizes "screenshot save <stem>" on whitespace, so squash
# anything shell-word-unsafe in the ADF basename to underscores.
tmp_stem="vamigaref_$$_$(printf '%s' "$stem" | tr -c 'A-Za-z0-9_-' '_')"
script="/tmp/${tmp_stem}.retrosh"
trap 'rm -f "$tmp_kick" "$tmp_adf" "$script" "/tmp/${tmp_stem}.raw"' EXIT
cp "$KICK" "$tmp_kick"
cp "$ADF" "$tmp_adf"

cat > "$script" <<EOF
# vAmiga reference script generated by tools/vamiga-ref.sh
regression setup $SETUP $tmp_kick
regression run $tmp_adf
wait $secs_int seconds
screenshot save $tmp_stem
EOF

"$VAHEADLESS" "$script" >/dev/null 2>&1

raw="/tmp/${tmp_stem}.raw"
if [ ! -f "$raw" ]; then
    echo "error: vAmiga produced no screenshot ($raw)" >&2
    exit 1
fi
mkdir -p "$(dirname "$OUT")"
mv "$raw" "$OUT"
echo "$OUT"
